# Configuraci√≥n de servidor
server:
  port: 8080  

spring:
  datasource:
    url: jdbc:postgresql://localhost/CIAdb
    username: postgres
    password: Nacionalcampeon04.
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: felipetrivinogarzon@gmail.com
    password: bccs bcmf vvmk gooc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 60000  
          timeout: 60000              
          writetimeout: 60000    
  
mercadopago:
  access-token: "APP_USR-3677142545763018-102808-b0d66c0b5bb678de301ae7d97c76dd6a-2951551977"  # tu token de PRUEBA
  base-url: https://api.mercadopago.com
  back-url-base: http://localhost:3000/pagos
  notification-url: "https://hydrocyanic-porfirio-unevenly.ngrok-free.dev/api/payments/webhook"


